### ISSUE TITLE
[Documentation] Any plans for more documentation on `org-roam`?

### ISSUE THREAD

**Issue by thecashewtrader** [theiceshelf/firn#107]
Hi,
As far as I have looked around, I am not aware of documentation specific to integration with `org-roam`, aside from a mention in https://firn.theiceshelf.com/setup. I was wondering if there is scope for more documentation regarding this?

Some specifics:

* `PROPERTIES` drawer hiding front matter: This seems to be addressed in #104
* An index page with a graph (could be omitted as the project wants to avoid JS) or some other overview
* Conversion of ugly `{timestamp}-{slug}.html` URLs to custom ones/just `{slug}` URLs

**Comment by teesloane** [comment]
Hi there!

I'm not planning on a tight integration with org-roam at the moment. At the moment, I use org-roam v1, and cannot migrate to v2 as I intend to continue to use `file:` links, which firn needs to have in order to build links between files (I do not know if that has changed). At the moment, I only really include the ability to use org_roam tags as part of a firn site.

Regarding #104  - I am currently exploring a re-write that may address this, but I can't promise anything (and  if something does get done, the breaking changes will be-a-plenty 🙃 )

> Conversion of ugly {timestamp}-{slug}.html URLs to custom ones/just {slug} URLs
I intend firn to be more inclined toward wiki-style sites, in which each page should have a unique name (`bicycles.org` -> `bicycles.html` etc). I will think about this problem though, as a user config flag could certainly handle this (although, it's a bit too granular a setting in my opinion).

**Comment by thecashewtrader** [comment]
Aight, understandable, closing. For people that came via search engines: I *might* do something with https://gitlab.com/thecashewtrader/org-notes . For now it has an auto generated index page, I'll look into trying out a links graph later.
