### ISSUE TITLE
support image captions

### ISSUE THREAD

**Issue by holtzermann17** [theiceshelf/firn#45]
Sample content:

> #+CAPTION: /A prototypical university. Caption reads: Wisconsin State University, Madison, Wis. 1879. Inset captions describe the pictured buildings: Ladies Hall, South Dormitory, University Hall, Assembly Halls & Library, North Dormitory, Science Hall, President's Residence, University Farm, and Washburn Observatory. Public domain./
> [[file:images/wisconsin-map.jpg]]

In regular HTML export:
![Screenshot from 2020-10-06 08-59-59](https://user-images.githubusercontent.com/179958/95174940-a3495f80-07b2-11eb-888e-c2835e414af5.png)

In Firn:
![Screenshot from 2020-10-06 09-03-12](https://user-images.githubusercontent.com/179958/95175049-cd9b1d00-07b2-11eb-8e33-bb435e9f707c.png)

**Comment by teesloane** [comment]
HI @holtzermann17  - thanks for the detailed issue. I did not know about the CAPTION functionality of org-mode.

The orgize parser would output the following from your sample above:

```json
{
  "type": "document",
  "children": [
    {
      "type": "section",
      "children": [
        {
          "type": "keyword",
          "key": "CAPTION",
          "value": "/A prototypical university. Caption reads: Wisconsin State University, Madison, Wis. 1879. Inset captions describe the pictured buildings: Ladies Hall, South Dormitory, University Hall, Assembly Halls & Library, North Dormitory, Science Hall, President's Residence, University Farm, and Washburn Observatory. Public domain./"
        },
        {
          "type": "paragraph",
          "children": [
            {
              "type": "link",
              "path": "file:images/wisconsin-map.jpg"
            }
          ]
        }
      ]
    }
  ]
}
```

I think it should be possible to do a "look-ahead" for when a caption is present and then swap the rendered output to have the caption below the element.

 I will probably have to table this for "investigation" in the meantime because:
- a similar implementation exists; when an image link is parsed, if it has description, it will create a similar effect; for example `[[file:data/files/vegas-mesa-2.JPG][The hill]]`, returns something to the same effect as your image posted.
  <img width="531" alt="image" src="https://user-images.githubusercontent.com/12987958/95351173-eb3db480-088e-11eb-8f08-11263c9fb7b3.png">
- More familiarity with org-mode is needed: I don't know too much about this side of org-mode, but it I think there are many capabilities in which a user can make use of `#+KEYWORDS` (for example, I do know they can be used to inline html). I think I will need to investigate what is possible here before writing an implementation for captions, especially if it's the case that a larger abstraction can be used.

Feel free to chime in, in either case, but especially regarding the latter. Thanks!

**Comment by yosevu** [comment]
A related problem I think, that I just noticed when I started to use images is that they don't have don't have [alt text](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img) makes them inaccessible for screen readers.

Org:
```org
#+CAPTION: "Moça com livro by Almeida Júnior"
#+ATTR_HTML: :alt "A painting of a young girl with a book. Moça com livro by Almeida Júnior by Almeida Júnior"
[[https://upload.wikimedia.org/wikipedia/commons/3/39/Almeida_J%C3%BAnior_-_Mo%C3%A7a_com_Livro.jpg][Moça com livro by  Almeida Júnior]]

```
HTML:
```html
<img width="1197" alt="Screen Shot 2020-10-14 at 11 52 39 PM" src="https://user-images.githubusercontent.com/16216104/96075119-5b909b00-0e78-11eb-9a83-a45294586e8f.png">
```

Would make sense to try to get these issues resolve upstream in orgize? I started looking for where the parsing happens here: https://github.com/PoiScript/orgize/blob/master/src/export/org.rs#L116.

**Comment by teesloane** [comment]
This might be better solved upstream. I have yet to figure out how to do a sort of "look-ahead" rendering mid-document, in which encountering org keywords (`#+____`) can be handled mid-document. 

The org-mode example you linked renders to this json with orgize:

```
{
  "type": "document",
  "children": [
    {
      "type": "section",
      "children": [
        {
          "type": "keyword",
          "key": "CAPTION",
          "value": "A black cat stalking a spider"
        },
        {
          "type": "keyword",
          "key": "ATTR_HTML",
          "value": ":alt cat/spider image :title Action! :align right"
        },
        {
          "type": "paragraph",
          "children": [
            {
              "type": "link",
              "path": "./img/a.jpg"
            }
          ]
        }
      ]
    }
  ]
}
```

Where `"value": ":alt cat/spider image :title Action! :align right"` would need a) be parsed to proper html and b) be configured to wrap the following child (or any successive child that follows a non-#+ keyword.  I'm interested in fixing this, but it will be in my backlog for quite some time probably.
