### ISSUE TITLE
Improving Orgize

### ISSUE THREAD

**Issue by jethrokuan** [theiceshelf/firn#47]
Hi!

I've been thinking of building a background process Org-roam using Orgize. Its responsibilities would be:

1. Building the database by iterating the Orgize datastructures for every org-roam file
2. Updating the database based on fsnotify events

Current Orgize doesn't support a number of things, like plain links (for e.g `cite:foo` links). I forked Orgize to implement those, and was wondering if firn would like to dogfood/improve Orgize as well.

https://github.com/jethrokuan/orgize

Depending on the success of the experiment, I might move the fork of Orgize into the org-roam organization and keep it maintained.

**Comment by teesloane** [comment]
Hey 👋 !

This is cool news. I will keep an eye on your fork and should be able to dog food it on a branch when some changes roll out. Currently, I have only run into a few small edge cases with Orgize and am still working out the larger features of Firn, so I might not get to it for a bit. That said, I'm glad you're looking into it, as I was a bit concerned that development might stall and that I might hit a block sooner or later. Thanks for the heads up!

**Comment by maisiliym** [comment]
Since this issue involves all the right people, here is a rare pointer:
https://github.com/200ok-ch/org-parser
Is (almost?) a de/serializer, which is potentially, due to the effects of synergy, *at least* an order of magnitude more beneficial than a parser (deserializer-only). This would, as everyone here could divine, allow org to become a *user interface* to data!

Note: This account does not usually respond back.
