### ISSUE TITLE
Support for Tailwind CSS

### ISSUE THREAD

**Issue by Emiller88** [theiceshelf/firn#62]
This is something I'd like to see that I had been thinking about. I'll update this issue with any progress I make on it in the future and update the docs if I'm successful.

**Comment by yosevu** [comment]
Yes please! I would personally like the option write my styles with Tailwind. Is there a way to do this so that Firn isn't prescriptive about the way styles are written? I People may prefer other styling frameworks or just plan CSS.

This is one reason that turned me away from another static site generator, Cryogen, which which leaned toward Selma and SASS.

**Comment by teesloane** [comment]
I think there might be two different sides to this issue - but I don't know Tailwind (although I do like it) enough to not ask questions

@Emiller88  is your original point about getting tailwind to actively analyze hiccup for css classes, and perform it's pruning of your compiled css files (I think that's what it does, no?)

Or is this about replacing firn's pre-baked-in styles with whatever you like?

If it's the latter, I think this would solve what you are raising @yosevu . We can create a config option to read in a `edn` file that maps the pre-determined firn elements (backlinks, table of contents, etc) and html elements to the generated hiccup. This file however, will be rather large and not particularly easy for folks to grok - documentation will be pretty important. I will think about this for a couple days because I do think it might be worth doing sooner than later.

**Comment by Emiller88** [comment]
> Or is this about replacing firn's pre-baked-in styles with whatever you like?

This one!

[Tailwind can be used via cdn](https://tailwindcss.com/docs/installation#using-tailwind-via-cdn) just link mvp.css. This wasn't to replace MVP as the default more so just allow user's to replace it with whatever they like, just like you said.

**Comment by teesloane** [comment]
A follow-up question. Couldn't one use the [apply functionality](https://tailwindcss.com/docs/extracting-components#extracting-component-classes-with-apply) of Tailwind with the firn baked in classes?

A user could erase `firn_base` css to remove all the default styling that comes with a Firn site, and then @apply classes to the baked-in css classes, such as `firn-backlinks` or `firn-sitemap` etc. 

I just want to make sure I understand the problem before considering what will likely end up being a pretty complex change.

**Comment by yosevu** [comment]
Do you mean to use the @apply directive for the pre-defined Firn classes @teesloane? If that is what you mean, it may not be worth it because it is still maintaining a separate stylesheet, albeit with Tailwind classes. I think that @apply could be useful for reusing certain styles, but the main draw of Tailwind for me is being able to write most of my styles with declarative utility classes on HTML elements (Hiccup elements in this case). This is the primary way of styling with Tailwind and where it is most powerful. 

Here is an example from a ClojureScript project that I used Tailwind on:

```clojurescript
(defn tag-template [tag]
  [:a.text-blue-600.text-sm.t.ml-3.border-b.border-transparent.hover:border-blue-600
   {:key tag
    :href (bidi/path-for
                   app-routes
                   :tag
                   :tag-id
                   tag)}
   tag])
```

![Screen Shot 2020-11-22 at 9 42 06 PM](https://user-images.githubusercontent.com/16216104/99925310-acaf6c80-2d0b-11eb-8850-8cf87603b26c.png)

I'm not sure how well this will work with Firn, but it would be great to have the flexibility to have the option to write styles like this!

**Comment by yosevu** [comment]
> > Or is this about replacing firn's pre-baked-in styles with whatever you like?
> 
> This one!
> 
> [Tailwind can be used via cdn](https://tailwindcss.com/docs/installation#using-tailwind-via-cdn) just link mvp.css. This wasn't to replace MVP as the default more so just allow user's to replace it with whatever they like, just like you said.

@Emiller88 Yes Tailwind can be used via cdn, but as I recall from the last time I used it this is severely limited and we would not be able to use all the Post CSS plugins such as like autoprefixer and Purge CSS, which is pretty important for reducing file size. Tailwind is best used with access to it's plugin system. For more info about this see this section of the [Installation documentation](https://tailwindcss.com/docs/installation#using-tailwind-via-cdn).

**Comment by teesloane** [comment]
@yosevu that makes sense. So if I'm understanding, the situation is:

- it's possible to use Tailwind with your Firn partials and layouts already (and Tailwind will properly tree shake unused classes)
- it is current not possible to internally decide what classes Firn's renderer components get (ie, calling `render :toc` is going to create a hiccup structure with baked-in `.firn-toc` classes, etc)

While I understand the value of not having to have any style sheets at all, if we make it so that the internal renderers are open to custom classes, a user will still have to create some kind of file (ex: "firn_styles.edn`) and store it in the `_firn` folder somewhere (and then refactor the code so that it's possible to apply those styles). 

So essentially, the same thing would be happening - an extra file would be created with declarations of classes. If this is the case, at least for now, I'd rather keep it that firn has pre-baked styles that can be altered with normal css/scss/tailwind @apply than to introduce a new api that needs documenting and explanation for more advanced users. 

Anyway, I'm not sure I'm still on the same page, so lets chat about it in the discord for any nuanced details I might be missing.

**Comment by yosevu** [comment]
Yeah, that makes sense to leave the internal Firn styles as is @teesloane and users can add frameworks like Tailwind to manage custom styles exernally.
