### ISSUE TITLE
Support for RSS specific layout

### ISSUE THREAD

**Issue by lyderichti59** [theiceshelf/firn#89]
The RSS feed file is filled with the whole HTML content of articles.

However, using the whole HTML including "article-unrelated" content (the CSS files, the script tags, the navbar, ...) breaks my RSS reader.
Here is a screenshot of the RSS file read with [Brief on Firefox](https://addons.mozilla.org/fr/firefox/addon/brief/) with the dark theme enabled.
[See screenshot](https://user-images.githubusercontent.com/34691216/107979004-0b5c4d80-6fbe-11eb-8cbb-1a558f2206f9.png)

I think of several ways to cover this : 
- Being deterministic and building a RSS specific HTML content for each processed org file (With a "render"-like function, but we may want to include a lot of tuning like ignoring headlines, ... )
- Let the user chose a layout himself (create a specific layout/rss.clj file for example) and specifying it in the config.  

In either case, the config could evolve from the `:enable-rss?` boolean to `:firn-rss` being false/nil when rss is disabled and a map with richer tuning when enabled, just like for `:firn-toc` 

What is you insight on this ? 
Let me know if I can contribute one way or the other, if I can allocate a bit of bandwidth on this.

**Comment by teesloane** [comment]
Salut @lyderichti59!

I have noticed this problem as well but haven't thought of a solution yet. I think something like your  first suggestion point might work. I think the easiest (but hackiest) way to do this would be to request users of Firn that for content to show up in an RSS feed  their layouts *must* use a [:main ...] [html tag](https://www.w3schools.com/tags/tag_main.asp) - because the main tag should only exist once per html document, after everything has been rendered and the XML is ready to be built; Firn could look for the main tag and extract a sub string that includes everything between `<main>` ... `</main>` tags and have it constitute the rss feed `description` key. That might be worth trying as the easiest approach first. 

I'm always happy to receive pull requests. The repo links to a discord where folks sometimes come and pair program on issues or ask questions, so feel free to drop by there if you have the bandwidth; otherwise I'll try and get to this in the coming week or two.

**Comment by teesloane** [comment]
Closed by #90
